name: SAST Scan

on: [push, pull_request]

jobs:
  scanning:
    name: SAST scan
    runs-on: ubuntu-latest
    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
        env:
          SCAN_DEBUG_MODE: debug
          VDB_HOME: ${{ github.workspace }}/db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
